server:
  port: 8180
spring:
  flyway:
    enabled: false
    locations: classpath:db/migration
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1 # En memoria RAM
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create-drop
  jackson:
    time-zone: Europe/Madrid
  h2:
    console.enabled: true
logging:
  level:
    root: INFO
